// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class FileNode {
    "name": string;
    "isDir": boolean;
    "size": number;
    "children": (FileNode | null)[];

    /** Creates a new FileNode instance. */
    constructor($$source: Partial<FileNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     */
    static createFrom($$source: any = {}): FileNode {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField3_0($$parsedSource["children"]);
        }
        return new FileNode($$parsedSource as Partial<FileNode>);
    }
}

export class FileTreeMap {
    "root": FileNode | null;

    /** Creates a new FileTreeMap instance. */
    constructor($$source: Partial<FileTreeMap> = {}) {
        if (!("root" in $$source)) {
            this["root"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileTreeMap instance from a string or object.
     */
    static createFrom($$source: any = {}): FileTreeMap {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("root" in $$parsedSource) {
            $$parsedSource["root"] = $$createField0_0($$parsedSource["root"]);
        }
        return new FileTreeMap($$parsedSource as Partial<FileTreeMap>);
    }
}

export class QueryResult {
    "columns": string[];
    "rows": any[][];
    "error": string;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class SQLiteResultOutput {
    "rowsAffected": number;
    "lastInsertId": number;
    "error": string;

    /** Creates a new SQLiteResultOutput instance. */
    constructor($$source: Partial<SQLiteResultOutput> = {}) {
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("lastInsertId" in $$source)) {
            this["lastInsertId"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLiteResultOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SQLiteResultOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SQLiteResultOutput($$parsedSource as Partial<SQLiteResultOutput>);
    }
}

// Private type creation functions
const $$createType0 = FileNode.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($$createType4);
