// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

/**
 * @param {string} a
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetHelloString(a) {
    let $resultPromise = /** @type {any} */($Call.ByID(1810706486, a));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Hello() {
    let $resultPromise = /** @type {any} */($Call.ByID(2264649841));
    return $resultPromise;
}
