// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

export function Attach(app: application$0.App | null, mainWindow: application$0.WebviewWindow | null): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(342809644, app, mainWindow) as any;
    return $resultPromise;
}

export function Init(CellClicked: any): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1671903899, CellClicked) as any;
    return $resultPromise;
}

export function LoadEnv(envContent: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2092664016, envContent) as any;
    return $resultPromise;
}
