// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2841246318);
}

export function Execute(query: string): $CancellablePromise<models$0.SQLiteResultOutput> {
    return $Call.ByID(913414865, query).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ExecuteQuery(query: string): $CancellablePromise<models$0.QueryResult> {
    return $Call.ByID(3595892903, query).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDB(): $CancellablePromise<gorm$0.DB | null> {
    return $Call.ByID(772526788).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetGorm(): $CancellablePromise<gorm$0.DB | null> {
    return $Call.ByID(1569253765).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetName(): $CancellablePromise<string> {
    return $Call.ByID(2086215133);
}

export function GetSQL(): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(2696950202).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSQLite(): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(2889310246).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Open(path: string, passwd: string): $CancellablePromise<void> {
    return $Call.ByID(2763850682, path, passwd);
}

export function RunQueryTest(): $CancellablePromise<void> {
    return $Call.ByID(2708218905);
}

export function RunSmallTest(): $CancellablePromise<void> {
    return $Call.ByID(710338514);
}

export function RunTransactionTest1(): $CancellablePromise<void> {
    return $Call.ByID(353677308);
}

// Private type creation functions
const $$createType0 = models$0.SQLiteResultOutput.createFrom;
const $$createType1 = models$0.QueryResult.createFrom;
const $$createType2 = gorm$0.DB.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = sql$0.DB.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
