// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetHelloString(a: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1810706486, a) as any;
    return $resultPromise;
}

export function Hello(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2264649841) as any;
    return $resultPromise;
}
