// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clause$0 from "./clause/models.js";

export class join {
    "Name": string;
    "Conds": any[];
    "On": clause$0.Where | null;
    "Selects": string[];
    "Omits": string[];
    "JoinType": clause$0.JoinType;

    /** Creates a new join instance. */
    constructor($$source: Partial<join> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Conds" in $$source)) {
            this["Conds"] = [];
        }
        if (!("On" in $$source)) {
            this["On"] = null;
        }
        if (!("Selects" in $$source)) {
            this["Selects"] = [];
        }
        if (!("Omits" in $$source)) {
            this["Omits"] = [];
        }
        if (!("JoinType" in $$source)) {
            this["JoinType"] = ("" as clause$0.JoinType);
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new join instance from a string or object.
     */
    static createFrom($$source: any = {}): join {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Conds" in $$parsedSource) {
            $$parsedSource["Conds"] = $$createField1_0($$parsedSource["Conds"]);
        }
        if ("On" in $$parsedSource) {
            $$parsedSource["On"] = $$createField2_0($$parsedSource["On"]);
        }
        if ("Selects" in $$parsedSource) {
            $$parsedSource["Selects"] = $$createField3_0($$parsedSource["Selects"]);
        }
        if ("Omits" in $$parsedSource) {
            $$parsedSource["Omits"] = $$createField4_0($$parsedSource["Omits"]);
        }
        return new join($$parsedSource as Partial<join>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = clause$0.Where.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
