// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as context$0 from "../../context/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clause$0 from "./clause/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logger$0 from "./logger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "./schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reflect$0 from "../../reflect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as strings$0 from "../../strings/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../../sync/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $internal from "./internal.js";

/**
 * ConnPool db conns pool interface
 */
export type ConnPool = any;

/**
 * DB GORM DB definition
 */
export class DB {
    /**
     * GORM perform single create, update, delete operations in transactions by default to ensure database data integrity
     * You can disable it by setting `SkipDefaultTransaction` to true
     */
    "SkipDefaultTransaction": boolean;

    /**
     * NamingStrategy tables, columns naming strategy
     */
    "NamingStrategy": schema$0.Namer;

    /**
     * FullSaveAssociations full save associations
     */
    "FullSaveAssociations": boolean;

    /**
     * Logger
     */
    "Logger": logger$0.Interface;

    /**
     * NowFunc the function to be used when creating a new timestamp
     */
    "NowFunc": any;

    /**
     * DryRun generate sql without execute
     */
    "DryRun": boolean;

    /**
     * PrepareStmt executes the given query in cached statement
     */
    "PrepareStmt": boolean;

    /**
     * DisableAutomaticPing
     */
    "DisableAutomaticPing": boolean;

    /**
     * DisableForeignKeyConstraintWhenMigrating
     */
    "DisableForeignKeyConstraintWhenMigrating": boolean;

    /**
     * IgnoreRelationshipsWhenMigrating
     */
    "IgnoreRelationshipsWhenMigrating": boolean;

    /**
     * DisableNestedTransaction disable nested transaction
     */
    "DisableNestedTransaction": boolean;

    /**
     * AllowGlobalUpdate allow global update
     */
    "AllowGlobalUpdate": boolean;

    /**
     * QueryFields executes the SQL query with all fields of the table
     */
    "QueryFields": boolean;

    /**
     * CreateBatchSize default create batch size
     */
    "CreateBatchSize": number;

    /**
     * TranslateError enabling error translation
     */
    "TranslateError": boolean;

    /**
     * PropagateUnscoped propagate Unscoped to every other nested statement
     */
    "PropagateUnscoped": boolean;

    /**
     * ClauseBuilders clause builder
     */
    "ClauseBuilders": { [_: string]: clause$0.ClauseBuilder };

    /**
     * ConnPool db conn pool
     */
    "ConnPool": ConnPool;

    /**
     * Dialector database dialector
     */
    "Dialector": Dialector;

    /**
     * Plugins registered plugins
     */
    "Plugins": { [_: string]: Plugin };
    "Error": any;
    "RowsAffected": number;
    "Statement": Statement | null;

    /** Creates a new DB instance. */
    constructor($$source: Partial<DB> = {}) {
        if (!("SkipDefaultTransaction" in $$source)) {
            this["SkipDefaultTransaction"] = false;
        }
        if (!("NamingStrategy" in $$source)) {
            this["NamingStrategy"] = null;
        }
        if (!("FullSaveAssociations" in $$source)) {
            this["FullSaveAssociations"] = false;
        }
        if (!("Logger" in $$source)) {
            this["Logger"] = null;
        }
        if (!("NowFunc" in $$source)) {
            this["NowFunc"] = null;
        }
        if (!("DryRun" in $$source)) {
            this["DryRun"] = false;
        }
        if (!("PrepareStmt" in $$source)) {
            this["PrepareStmt"] = false;
        }
        if (!("DisableAutomaticPing" in $$source)) {
            this["DisableAutomaticPing"] = false;
        }
        if (!("DisableForeignKeyConstraintWhenMigrating" in $$source)) {
            this["DisableForeignKeyConstraintWhenMigrating"] = false;
        }
        if (!("IgnoreRelationshipsWhenMigrating" in $$source)) {
            this["IgnoreRelationshipsWhenMigrating"] = false;
        }
        if (!("DisableNestedTransaction" in $$source)) {
            this["DisableNestedTransaction"] = false;
        }
        if (!("AllowGlobalUpdate" in $$source)) {
            this["AllowGlobalUpdate"] = false;
        }
        if (!("QueryFields" in $$source)) {
            this["QueryFields"] = false;
        }
        if (!("CreateBatchSize" in $$source)) {
            this["CreateBatchSize"] = 0;
        }
        if (!("TranslateError" in $$source)) {
            this["TranslateError"] = false;
        }
        if (!("PropagateUnscoped" in $$source)) {
            this["PropagateUnscoped"] = false;
        }
        if (!("ClauseBuilders" in $$source)) {
            this["ClauseBuilders"] = {};
        }
        if (!("ConnPool" in $$source)) {
            this["ConnPool"] = null;
        }
        if (!("Dialector" in $$source)) {
            this["Dialector"] = null;
        }
        if (!("Plugins" in $$source)) {
            this["Plugins"] = {};
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }
        if (!("RowsAffected" in $$source)) {
            this["RowsAffected"] = 0;
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DB instance from a string or object.
     */
    static createFrom($$source: any = {}): DB {
        const $$createField16_0 = $$createType0;
        const $$createField19_0 = $$createType1;
        const $$createField22_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ClauseBuilders" in $$parsedSource) {
            $$parsedSource["ClauseBuilders"] = $$createField16_0($$parsedSource["ClauseBuilders"]);
        }
        if ("Plugins" in $$parsedSource) {
            $$parsedSource["Plugins"] = $$createField19_0($$parsedSource["Plugins"]);
        }
        if ("Statement" in $$parsedSource) {
            $$parsedSource["Statement"] = $$createField22_0($$parsedSource["Statement"]);
        }
        return new DB($$parsedSource as Partial<DB>);
    }
}

/**
 * Dialector GORM database dialector
 */
export type Dialector = any;

/**
 * Plugin GORM plugin interface
 */
export type Plugin = any;

/**
 * Statement statement
 */
export class Statement {
    /**
     * GORM perform single create, update, delete operations in transactions by default to ensure database data integrity
     * You can disable it by setting `SkipDefaultTransaction` to true
     */
    "SkipDefaultTransaction": boolean;

    /**
     * NamingStrategy tables, columns naming strategy
     */
    "NamingStrategy": schema$0.Namer;

    /**
     * FullSaveAssociations full save associations
     */
    "FullSaveAssociations": boolean;

    /**
     * Logger
     */
    "Logger": logger$0.Interface;

    /**
     * NowFunc the function to be used when creating a new timestamp
     */
    "NowFunc": any;

    /**
     * DryRun generate sql without execute
     */
    "DryRun": boolean;

    /**
     * PrepareStmt executes the given query in cached statement
     */
    "PrepareStmt": boolean;

    /**
     * DisableAutomaticPing
     */
    "DisableAutomaticPing": boolean;

    /**
     * DisableForeignKeyConstraintWhenMigrating
     */
    "DisableForeignKeyConstraintWhenMigrating": boolean;

    /**
     * IgnoreRelationshipsWhenMigrating
     */
    "IgnoreRelationshipsWhenMigrating": boolean;

    /**
     * DisableNestedTransaction disable nested transaction
     */
    "DisableNestedTransaction": boolean;

    /**
     * AllowGlobalUpdate allow global update
     */
    "AllowGlobalUpdate": boolean;

    /**
     * QueryFields executes the SQL query with all fields of the table
     */
    "QueryFields": boolean;

    /**
     * CreateBatchSize default create batch size
     */
    "CreateBatchSize": number;

    /**
     * TranslateError enabling error translation
     */
    "TranslateError": boolean;

    /**
     * PropagateUnscoped propagate Unscoped to every other nested statement
     */
    "PropagateUnscoped": boolean;

    /**
     * ClauseBuilders clause builder
     */
    "ClauseBuilders": { [_: string]: clause$0.ClauseBuilder };

    /**
     * Dialector database dialector
     */
    "Dialector": Dialector;

    /**
     * Plugins registered plugins
     */
    "Plugins": { [_: string]: Plugin };
    "Error": any;
    "RowsAffected": number;
    "Statement": Statement | null;
    "TableExpr": clause$0.Expr | null;
    "Table": string;
    "Model": any;
    "Unscoped": boolean;
    "Dest": any;
    "ReflectValue": reflect$0.Value;
    "Clauses": { [_: string]: clause$0.Clause };
    "BuildClauses": string[];
    "Distinct": boolean;

    /**
     * selected columns
     */
    "Selects": string[];

    /**
     * omit columns
     */
    "Omits": string[];

    /**
     * map columns
     */
    "ColumnMapping": { [_: string]: string };
    "Joins": $internal.join[];
    "Preloads": { [_: string]: any[] };
    "Settings": sync$0.Map;
    "ConnPool": ConnPool;
    "Schema": schema$0.Schema | null;
    "Context": context$0.Context;
    "RaiseErrorOnNotFound": boolean;
    "SkipHooks": boolean;
    "SQL": strings$0.Builder;
    "Vars": any[];
    "CurDestIndex": number;

    /** Creates a new Statement instance. */
    constructor($$source: Partial<Statement> = {}) {
        if (!("SkipDefaultTransaction" in $$source)) {
            this["SkipDefaultTransaction"] = false;
        }
        if (!("NamingStrategy" in $$source)) {
            this["NamingStrategy"] = null;
        }
        if (!("FullSaveAssociations" in $$source)) {
            this["FullSaveAssociations"] = false;
        }
        if (!("Logger" in $$source)) {
            this["Logger"] = null;
        }
        if (!("NowFunc" in $$source)) {
            this["NowFunc"] = null;
        }
        if (!("DryRun" in $$source)) {
            this["DryRun"] = false;
        }
        if (!("PrepareStmt" in $$source)) {
            this["PrepareStmt"] = false;
        }
        if (!("DisableAutomaticPing" in $$source)) {
            this["DisableAutomaticPing"] = false;
        }
        if (!("DisableForeignKeyConstraintWhenMigrating" in $$source)) {
            this["DisableForeignKeyConstraintWhenMigrating"] = false;
        }
        if (!("IgnoreRelationshipsWhenMigrating" in $$source)) {
            this["IgnoreRelationshipsWhenMigrating"] = false;
        }
        if (!("DisableNestedTransaction" in $$source)) {
            this["DisableNestedTransaction"] = false;
        }
        if (!("AllowGlobalUpdate" in $$source)) {
            this["AllowGlobalUpdate"] = false;
        }
        if (!("QueryFields" in $$source)) {
            this["QueryFields"] = false;
        }
        if (!("CreateBatchSize" in $$source)) {
            this["CreateBatchSize"] = 0;
        }
        if (!("TranslateError" in $$source)) {
            this["TranslateError"] = false;
        }
        if (!("PropagateUnscoped" in $$source)) {
            this["PropagateUnscoped"] = false;
        }
        if (!("ClauseBuilders" in $$source)) {
            this["ClauseBuilders"] = {};
        }
        if (!("Dialector" in $$source)) {
            this["Dialector"] = null;
        }
        if (!("Plugins" in $$source)) {
            this["Plugins"] = {};
        }
        if (!("Error" in $$source)) {
            this["Error"] = null;
        }
        if (!("RowsAffected" in $$source)) {
            this["RowsAffected"] = 0;
        }
        if (!("Statement" in $$source)) {
            this["Statement"] = null;
        }
        if (!("TableExpr" in $$source)) {
            this["TableExpr"] = null;
        }
        if (!("Table" in $$source)) {
            this["Table"] = "";
        }
        if (!("Model" in $$source)) {
            this["Model"] = null;
        }
        if (!("Unscoped" in $$source)) {
            this["Unscoped"] = false;
        }
        if (!("Dest" in $$source)) {
            this["Dest"] = null;
        }
        if (!("ReflectValue" in $$source)) {
            this["ReflectValue"] = (new reflect$0.Value());
        }
        if (!("Clauses" in $$source)) {
            this["Clauses"] = {};
        }
        if (!("BuildClauses" in $$source)) {
            this["BuildClauses"] = [];
        }
        if (!("Distinct" in $$source)) {
            this["Distinct"] = false;
        }
        if (!("Selects" in $$source)) {
            this["Selects"] = [];
        }
        if (!("Omits" in $$source)) {
            this["Omits"] = [];
        }
        if (!("ColumnMapping" in $$source)) {
            this["ColumnMapping"] = {};
        }
        if (!("Joins" in $$source)) {
            this["Joins"] = [];
        }
        if (!("Preloads" in $$source)) {
            this["Preloads"] = {};
        }
        if (!("Settings" in $$source)) {
            this["Settings"] = (new sync$0.Map());
        }
        if (!("ConnPool" in $$source)) {
            this["ConnPool"] = null;
        }
        if (!("Schema" in $$source)) {
            this["Schema"] = null;
        }
        if (!("Context" in $$source)) {
            this["Context"] = null;
        }
        if (!("RaiseErrorOnNotFound" in $$source)) {
            this["RaiseErrorOnNotFound"] = false;
        }
        if (!("SkipHooks" in $$source)) {
            this["SkipHooks"] = false;
        }
        if (!("SQL" in $$source)) {
            this["SQL"] = (new strings$0.Builder());
        }
        if (!("Vars" in $$source)) {
            this["Vars"] = [];
        }
        if (!("CurDestIndex" in $$source)) {
            this["CurDestIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Statement instance from a string or object.
     */
    static createFrom($$source: any = {}): Statement {
        const $$createField16_0 = $$createType0;
        const $$createField18_0 = $$createType1;
        const $$createField21_0 = $$createType3;
        const $$createField22_0 = $$createType5;
        const $$createField27_0 = $$createType6;
        const $$createField28_0 = $$createType8;
        const $$createField29_0 = $$createType9;
        const $$createField31_0 = $$createType9;
        const $$createField32_0 = $$createType9;
        const $$createField33_0 = $$createType10;
        const $$createField34_0 = $$createType12;
        const $$createField35_0 = $$createType14;
        const $$createField36_0 = $$createType15;
        const $$createField38_0 = $$createType17;
        const $$createField42_0 = $$createType18;
        const $$createField43_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ClauseBuilders" in $$parsedSource) {
            $$parsedSource["ClauseBuilders"] = $$createField16_0($$parsedSource["ClauseBuilders"]);
        }
        if ("Plugins" in $$parsedSource) {
            $$parsedSource["Plugins"] = $$createField18_0($$parsedSource["Plugins"]);
        }
        if ("Statement" in $$parsedSource) {
            $$parsedSource["Statement"] = $$createField21_0($$parsedSource["Statement"]);
        }
        if ("TableExpr" in $$parsedSource) {
            $$parsedSource["TableExpr"] = $$createField22_0($$parsedSource["TableExpr"]);
        }
        if ("ReflectValue" in $$parsedSource) {
            $$parsedSource["ReflectValue"] = $$createField27_0($$parsedSource["ReflectValue"]);
        }
        if ("Clauses" in $$parsedSource) {
            $$parsedSource["Clauses"] = $$createField28_0($$parsedSource["Clauses"]);
        }
        if ("BuildClauses" in $$parsedSource) {
            $$parsedSource["BuildClauses"] = $$createField29_0($$parsedSource["BuildClauses"]);
        }
        if ("Selects" in $$parsedSource) {
            $$parsedSource["Selects"] = $$createField31_0($$parsedSource["Selects"]);
        }
        if ("Omits" in $$parsedSource) {
            $$parsedSource["Omits"] = $$createField32_0($$parsedSource["Omits"]);
        }
        if ("ColumnMapping" in $$parsedSource) {
            $$parsedSource["ColumnMapping"] = $$createField33_0($$parsedSource["ColumnMapping"]);
        }
        if ("Joins" in $$parsedSource) {
            $$parsedSource["Joins"] = $$createField34_0($$parsedSource["Joins"]);
        }
        if ("Preloads" in $$parsedSource) {
            $$parsedSource["Preloads"] = $$createField35_0($$parsedSource["Preloads"]);
        }
        if ("Settings" in $$parsedSource) {
            $$parsedSource["Settings"] = $$createField36_0($$parsedSource["Settings"]);
        }
        if ("Schema" in $$parsedSource) {
            $$parsedSource["Schema"] = $$createField38_0($$parsedSource["Schema"]);
        }
        if ("SQL" in $$parsedSource) {
            $$parsedSource["SQL"] = $$createField42_0($$parsedSource["SQL"]);
        }
        if ("Vars" in $$parsedSource) {
            $$parsedSource["Vars"] = $$createField43_0($$parsedSource["Vars"]);
        }
        return new Statement($$parsedSource as Partial<Statement>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = Statement.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = clause$0.Expr.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = reflect$0.Value.createFrom;
const $$createType7 = clause$0.Clause.createFrom;
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $internal.join.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = $Create.Map($Create.Any, $$createType13);
const $$createType15 = sync$0.Map.createFrom;
const $$createType16 = schema$0.Schema.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = strings$0.Builder.createFrom;
